import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

type Props = {}

const Blogs = (props: Props) => {
  return (
    <div>Blogs</div>
  )
}

export default Blogs