import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

const About = () => {
  return (
    <div>About</div>
  )
}

export default About