import { Typography } from '@mui/material'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

const Create = () => {
  return (
   <Typography variant='h1'>HELLO</Typography>
  )
}

export default Create