import BlogForm from '@/components/BlogForm'
import { Box, Typography } from '@mui/material'
import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
  title: 'About',
  description: 'Generated by create next app',
}

const Create = () => {

  return (
    <>
      <Box sx={{ display: "flex", flexDirection: "column", justifyContent: "center" }}>
        <Typography variant='h2' textAlign="center">
          Create a new Blog
        </Typography>
        <BlogForm />
      </Box>
    </>
  )
}

export default Create